remote_theme: "mmistakes/minimal-mistakes"

# title: "Poornima S Jain"
description: "PHD Scholar | Artificial Intelligence | IIT Hyderabad"
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag

author: poornima

sass:
  style: compressed

include:
  - assets/css

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
