remote_theme: "mmistakes/minimal-mistakes"

# title: "Poornima S Jain"
description: "PHD Scholar | Artificial Intelligence | IIT Hyderabad"
plugins:
  - jekyll-include-cache

author: poornima

# Optional: social links, analytics, etc.
